---
name: GH Action Lint
on:
  pull_request:
    paths:
      - ".github/workflows/**"
  merge_group:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  gh-action-lint:
    name: GH Action Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run the actionlint action
        uses: reviewdog/action-actionlint@664c8ef5435569dd2880e62d891ab3ecdf98dc60
