---
name: Dockerfile Lint
on:
  pull_request:
    paths:
      - "Dockerfile"
  merge_group:

permissions:
  contents: read

jobs:
  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Run the hadolint action
        uses: hadolint/hadolint-action@3285327e7ad2e137653f6da3d6640d30c05b9e1d
