---
name: Lint
on: pull_request

permissions:
  contents: read

jobs:
  dockerfile:
    name: dockerfile
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf

  markdownlint:
    name: markdown
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e

  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281

  yamllint:
    name: Yamllint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run Yamllint
        uses: frenck/action-yamllint@823b6c0787cee7a1636499ab89a2de60ecd43155
        with:
          strict: true
