---
name: Lint
on: pull_request

permissions:
  contents: read

jobs:
  dockerfile:
    name: dockerfile
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run hadolint
        uses: hadolint/hadolint-action@d292784f8f3eacda47060b259a580467b0ba410c

  markdownlint:
    name: markdown
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@e63bd6f381371b3843e5d04c9e957e1a29453f31

  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - uses: reviewdog/action-actionlint@664c8ef5435569dd2880e62d891ab3ecdf98dc60

  yamllint:
    name: Yamllint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run Yamllint
        uses: frenck/action-yamllint@823b6c0787cee7a1636499ab89a2de60ecd43155
        with:
          strict: true
