---
name: Markdown Lint
on:
  pull_request:
    paths:
      - "*.md"
      - ".github/*.md"
      - ".github/ISSUE_TEMPLATE/**"
  merge_group:

permissions:
  contents: read

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout the repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Run the markdownlint action
        uses: DavidAnson/markdownlint-cli2-action@70dbff992f5cf6124a6fc5bb4b56aef6f8daa232
