---
name: Markdown Lint
on:
  pull_request:
    paths:
      - "*.md"
      - ".github/*.md"
      - ".github/ISSUE_TEMPLATE/**"
  merge_group:

permissions:
  contents: read

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout the repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Run the markdownlint action
        uses: DavidAnson/markdownlint-cli2-action@4db3dfc2cb719a5a152cb38efef6e2e50db98973
